# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Get Latest Tag
      # You may pin to the exact commit or the version.
      # uses: WyriHaximus/github-action-get-previous-tag@7cf31075d206b1a0341e09ef4305949a73ab599b
      uses: WyriHaximus/github-action-get-previous-tag@v1.0.1
    - name: PowerShell script
      # You may pin to the exact commit or the version.
      # uses: Amadevus/pwsh-script@1f1751bbf3d1a92127bfc6c32403283625880cbf
      uses: Amadevus/pwsh-script@v2.0.1
      with:
        # PowerShell script to execute in Actions-hydrated context
        script: |
          write-host ${{ steps.previoustag.outputs.tag }}
    - name: GH Release
      # You may pin to the exact commit or the version.
      # uses: softprops/action-gh-release@b7e450da2a4b4cb4bfbae528f788167786cfcedf
      uses: softprops/action-gh-release@v0.1.5
      with:
        # Newline-delimited list of path globs for asset files to upload
        files: build/libs/Authme.jar
