# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

env:
  GITHUB_TOKEN: ${{ github.token }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Get the latest release upload url, tag, date
      id: latest_release_info
      uses: jossef/action-latest-release-info@v1.1.0
    - name: PowerShell script
      uses: Amadevus/pwsh-script@v2.0.1
      with:
        continue-on-error: true
        script: |
          echo "lala"
          echo "${{ steps.latest_release_info.outputs.tag_name }}"
          $semver = [System.Management.Automation.SemanticVersion] ${{ steps.latest_release_info.outputs.tag_name }}
          Write-ActionWarning ($semver | Format-Table | Out-String)
          Invoke-ActionNoCommandsBlock -GenerateToken {
            # this won't result in any workflow commands
            Write-Host $semver
            Write-Host ($semver | Format-Table | Out-String)
            Write-ActionError "not interpreted as error"
          }
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      with:
        # Newline-delimited list of path globs for asset files to upload
        files: build/libs/Authme.jar
