# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

env:
  GITHUB_TOKEN: ${{ github.token }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Get the latest release upload url, tag, date
      id: latest_release_info
      uses: jossef/action-latest-release-info@v1.1.0
    - name: PowerShell script
      uses: Amadevus/pwsh-script@v2.0.1
      id: bump_version_for_latest_tag
      with:
        continue-on-error: true
        script: |
          write-host "lala"
          write-host "${{ steps.latest_release_info.outputs.tag_name }}"
          $semver = [System.Management.Automation.SemanticVersion]::New("${{ steps.latest_release_info.outputs.tag_name }}")
          $semver = [System.Management.Automation.SemanticVersion]::New($semver.Major+1,$semver.Minor,$semver.Patch)
          Write-Host ($semver | Format-Table | Out-String)
          return $semver.ToString()
          
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      with:
        # Newline-delimited list of path globs for asset files to upload
        files: build/libs/Authme.jar
        tag_name: ${{ steps.bump_version_for_latest_tag.outputs.result }}
        
